server:
  port: 8082
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost
    gateway:
      routes:
        - id: user-service
          uri: lb://userservice
          predicates:
            - Path=/userservice/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/orderservice/**
          filters:
            - StripPrefix=1